### ISSUE TITLE
No shared memory access between different base-images

### ISSUE THREAD

**Issue by SeWieland** [Project-OSRM/osrm-backend#5164]
THIS IS NOT AN ACUTAL ISSUE
**Just in case someone stumbles upon the same problem as me**
--
### Background:
As already similarly discussed in #5134, I have a setup in which I need multiple OSRM instances (which access the same dataset).
So first I tested the following setup (streamlined version) using docker-compose (of course the *.osrm files have to be created in first place) and was amazed - **works great**! :+1: 

_Side note: the `/tmp` volume is **mandatory** due to the lockfiles and you have to keep the datastore container running somehow after everthing is in memory!
Also starting the "client" osrm-routed instances too early can cause problems - so just be sure to start up the datastore container first, check the logs, and you're good._

```
version: '2.1'
services:
  osrm-datastore:
    image: osrm/osrm-backend:v5.18.0
    container_name: osrm-datastore
    volumes:
      - /srv/container/osrm/data:/data
      - /tmp
    command: sh -c "osrm-datastore --dataset-name map /data/map.osrm && sh"
    sysctls:
      - kernel.shmall=1152921504606846720
      - kernel.shmmax=18446744073709551615
    ulimits:
      memlock:
        soft: 68719476736
        hard: 68719476736      
    tty: true
    stdin_open: true

  osrm-routing:
    image: osrm/osrm-backend:v5.18.0
    container_name: osrm-routing
    ipc: container:osrm-datastore
    depends_on:
      - osrm-datastore
    volumes_from:
      - osrm-datastore
    command: osrm-routed --shared-memory --dataset-name map

  osrm-routing-two:
    image: osrm/osrm-backend:v5.18.0
    container_name: osrm-routing-two
    ipc: container:osrm-datastore
    depends_on:
      - osrm-datastore
    volumes_from:
      - osrm-datastore
    command: osrm-routed --shared-memory --dataset-name map
```
#### Specific Case
One of my services is an "osrm-routed" instance and on the other one a custom (highly CPU-intensive) FCGI C++ application, which uses the **libosrm.a** library to access the shared memory.
To use OSRM as a buildstage-base container, I modified the Dockerfile (v5.18.0) - the libraries get stripped of in the official version.
So in the end, there are three stages:
 - Build OSRM _with_ libraries
 - Build my application using the existing build environment
 - Install runtime deps + copy over binaries to the same base-image as OSRM

So far, so good.
Since I have dependencies in my application that cannot be installed directly from the alpine repositories, I soon thought it would be a lot easier to rebuild the OSRM image using a **different base-image** at the cost of some space (I don't really care).

#### Custom Dockerfile (only the first stage):
I built the following Image
_Side note: do not use this for deployment, as it is obviously huge and just useful for building custom apps._
```
FROM ubuntu:18.04

RUN mkdir -p /src  && mkdir -p /opt
COPY . /src
WORKDIR /src

RUN NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
    apt update && \ 
    apt install -y build-essential git cmake pkg-config \
    libbz2-dev libstxxl-dev libstxxl1v5 libxml2-dev \
    libzip-dev libboost-all-dev lua5.2 liblua5.2-dev libtbb-dev \
    libluabind-dev libluabind0.9.1v5 && \
    echo "Building OSRM" && \
    git show --format="%H" | head -n1 > /opt/OSRM_GITSHA && \
    echo "Building OSRM gitsha $(cat /opt/OSRM_GITSHA)" && \
    mkdir -p build && \
    cd build && \
    BUILD_TYPE="Release" && \
    ENABLE_ASSERTIONS="Off" && \
    BUILD_TOOLS="Off" && \
    echo "Building ${BUILD_TYPE} with ENABLE_ASSERTIONS=${ENABLE_ASSERTIONS} BUILD_TOOLS=${BUILD_TOOLS}" && \
    cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_ASSERTIONS=${ENABLE_ASSERTIONS} -DBUILD_TOOLS=${BUILD_TOOLS} -DENABLE_LTO=On && \
    make -j${NPROC} install && \
    cd ../profiles && \
    cp -r * /opt && \
    \
    strip /usr/local/bin/* && \
    rm -rf /src
```
### Issue
**The image builds well and is working** in normal mode (no shared-mem)!
However, starting in shared-memory mode hangs the whole container - without error message or crash.
When switching into the container, after loading the shared memory container, using `docker exec -it osrm-backend sh` followed by `osrm-routed -s`, the following output is given:

```
[info] starting up engines, v5.18.0
[info] Loading from shared memory
[info] Threads: 16
[info] IP address: 0.0.0.0
[info] IP port: 5000
```
That's it. You actually have to `docker kill osrm-backend` from another shell, as you can't even exit the container any more. _Everything else_ works as expected.
The same applies as well for containerized applications using the library.
This way, I had to find out that OSRM instances based on different base-images are **NOT compatible** in shared-memory mode.

**Use the custom base-image as well for the datastore container!**

I guess this is not really a OSRM limitation, however in my rare use case you will encounter it :smile: 

#### Further Issue
When I was desperately looking for a solution, I managed it as well to get my application correctĺy compiled in the Alpine-based version of the container.
Interestingly, the **access time has quadrupled!** :no_good_man:

_Same Request (worst case):_
Ubuntu Based: 800ms
Alpine Based: 3500ms (**!**)

I guess the issue here is _musl_ as the standard libc under Alpine, but I'm not quite sure. However, this should be highly dependent on the specific case.
