### ISSUE TITLE
Error while using Docker-Container: Error while loading shared libraries

### ISSUE THREAD

**Issue by patreu22** [Project-OSRM/osrm-backend#5294]
Hello there,  

I've got the following (extract) of a Docker-compose file:  
```
  osrm-server:
    image: osrm/osrm-backend
    build:
      context: .
      dockerfile: ./osrm/Dockerfile.osrm
    ports:
      - 5000:5000
    command: bash -c "osrm-routed --algorithm mld berlin-latest.osrm"
```

The Dockerfile.osrm looks like this:  
```
FROM osrm/osrm-backend
RUN apt-get update
RUN apt-get install -y wget
RUN wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
RUN osrm-extract -p /opt/car.lua berlin-latest.osm.pbf
RUN osrm-partition berlin-latest.osrm
RUN osrm-customize berlin-latest.osrm
EXPOSE 5000
```  

But now the osrm-extract command is throwing an error:
```
osrm-extract: error while loading shared libraries: libboost_program_options.so.1.67.0: cannot open shared object file: No such file or directory
ERROR: Service 'osrm-server' failed to build: The command '/bin/sh -c osrm-extract -p /opt/car.lua berlin-latest.osm.pbf' returned a non-zero code: 127
```

We tested the same Dockerfile + Docker-compose on another machine and it works there, does anybody now how to fix it?

**Comment by goggel** [comment]
Same problem with Docker Version 2.0.0.0-mac81 (29211) (Engine: 18.09.0) and osrm/osrm-backend:latest 349bb0747a29 without further configuration.

**Comment by patreu22** [comment]
Please keep me informed if you make any new progress. I tried to uninstall and reinstall Docker, but it didn't help. My setup is equal to yours, I'm also working on a Mac machine.

I think it would be really great to get some help by some core developers here :)

**Comment by eguarc** [comment]
no anda nada, viejo

**Comment by goggel** [comment]
Using tag v5.20.0 fixes the problem and i would guess that switching the image to debian (f978900ab) causes the issue.
I'm a bit confused that latest is not the latest relase but seems to be the current master. Would it not make sense to point latest to the lastest release and use a tag develop/beta/master or something similar for current developments.

**Comment by eguarc** [comment]
I have deployed again forcing the tag to v5.20.0 and it works fine.

TAG:
osrm/osrm-backend:v5.20.0@sha256:23c75d40c83b287476e0ea0883dfe7c06c3d54302d41df343c36079b8a06f36e

thanks!

**Comment by patreu22** [comment]
Also did the trick for me, v5.20.0 works! For anybody following up that workaround: Keep in mind that you have to use apk instead of apt-get and Shell instead of Bash.
I'll keep that issue open so maybe some of the developers are interested into tracking down that bug.

Thx @goggel :)

**Comment by Stan92** [comment]
Hi @patreu22 
I follow the different step you said. I was able to create the image but running the docker-compose, I got errors like Missing/broken files : france-latest-osrm.osrm.ramIndex, france-latest-osrm.osrm.fileIndex, etc... with a final message "required files are missing".

my dockerfile looks like  : 

```
FROM osrm/osrm-backend:v5.20.0
RUN apk update
RUN apk add ca-certificates wget && update-ca-certificates
RUN wget http://download.geofabrik.de/europe/france-latest.osm.pbf
RUN osrm-extract -p /opt/car.lua france-latest.osm.pbf
RUN osrm-partition france-latest.osrm
RUN osrm-customize france-latest.osrm
EXPOSE 5000

```

and my compose file 

```
version: '3'
services:
  osrm-server:
    image: ssr-osrm-backend2
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: sh -c "osrm-routed --algorithm mld france-latest-osrm"

```

I do admit, I m new to docker. I suppose I missed something..
