### ISSUE TITLE
Deploy the container in kubernetes

### ISSUE THREAD

**Issue by luishensruiz** [Project-OSRM/osrm-backend#5585]
Hello OSRM devs,
first if all, thanks a lot for your work with this API.

The docker api works perfectly, but for a personal project, I'm trying to deploy it in Kubernetes. But it is failling everytime. The container is in "crashloop" state and also is not generating any logs.

My pod descriptor is very simple:
```
apiVersion: v1
kind: Pod
metadata:
  name: osrm-backend
  labels:
    app: osrm-backend    
spec:
  containers:
    - name: osrm-backend
      image: osrm/osrm-backend        
      ports:
      - containerPort: 5000
```

Do the backend container supports k8s? 
I think the descriptor is correct. With one similar I have deployed your osrm-frontend container in k8s with no problem at all.

Thanks in advance for your answers and again, congratulatiosn for this software ;)

**Comment by danpat** [comment]
@luishens01 Are you passing some parameters to the `osrm-routed` process to start your osrm-backend container?  It has mandatory command-line parameters (i.e. the routing datafile) that you don't appear to be passing in.

**Comment by luishens01** [comment]
Hello, 
are this params mandatory only for deploy in k8s?

For docker deploy, que execute It With a simple:

docker run -p 5000:5000 osrm/osrm-backend,

Later we added the file and execute the commands (partición, etc) for start working.

Pd: Thanks for you quickly replay

**Comment by danpat** [comment]
@luishens01 I'm not sure how that can possibly work.

The OSRM Dockerfile here:

https://github.com/Project-OSRM/osrm-backend/blob/master/docker/Dockerfile#L49

has no default command.  If you just do `docker run -p 5000:5000 osrm/osrm-backend`, it will exit immediately and do nothing.  I just did this locally, and sure enough, it simply exits without doing anything.

**Comment by luishens01** [comment]
We deployed it in docker with this sequence and it worked:

```
docker run -dit --network osrm -p 5000:5000 -p 5001:5001 -p 5002:5002 --name osrm-backend osrm/osrm-backend

docker cp our_map.pbf osrm-backend:/opt/car/our_map.pbf
docker exec -ti osrm-backend osrm-extract -p /opt/car.lua /opt/car/our_map.pbf
docker exec -ti osrm-backend osrm-partition /opt/car/our_map.osrm
docker exec -ti osrm-backend osrm-customize /opt/car/our_map.osrm
docker exec -ti osrm-backend osrm-routed --port 5000 --algorithm mld /opt/car/our_map.osrm
```

Going back to Kubernetes, I'm going to try the deployment passing the variables, and will tell you if it works. Thank you

**Comment by luishens01** [comment]
Hello, I made a new yaml descriptor for our custom container and now is working in k8s.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: osrm-backend
spec:
  selector:
    matchLabels:
      app: osrm-backend
  template:
    metadata:
      labels:
        app: osrm-backend
    spec:
      containers:
      - name: osrm-backend
        image: osrm-backend:custom
        command: ["osrm-routed"]
        args: ["--port", "5000", "--algorithm", "mld", "/opt/car/our_custom_map.osrm"]
        ports:
        - containerPort: 5000
```

Thanks a lot for your support! 

You can close thi issue.
