### ISSUE TITLE
Deployment of OSRM to Azure Kubernetes Service

### ISSUE THREAD

**Issue by sheldonreddy** [Project-OSRM/osrm-backend#5638]
Hi All, 

I have successfully deployed `OSRM-Backend` to an Azure Container Instance and am able to make requests to the corresponding endpoints and obtain the desired results. The `OSRM-Backend` image I used is from the `OSRM-Backend` Dockerhub repository. 

Now that I have tested this successfully, I want to now focus on Kubernetes for the Ochestration of my OSRM Docker containers. 

Azure provides the Azure Kubernetes Service (AKS) which I would like to deploy OSRM within. 
To do this, I have:

1. Successfully created an Azure Resource Group to host my Kubernetes Cluster
2. Successfully created an Azure Kubernetes Cluster
3. Unsuccessfully attempted to `Create A Resource` on the Kubernetes Dashboard using the OSRM-Backend Dockerhub image. To open the Kubernetes Dashboard I followed the instructions under `View Kubernetes Dashboard` found on my Kubernetes Cluster `Overview ` page. I used the Azure Cloud Shell to execute the commands listed in the instructions.

Once the Kubernetes Dashboard was opened, I clicked the `+CREATE` button in my attempts to Create a Resource. Here I pointed to the resource to the `OSRM-Backend` Image on Dockerhub and selected 2 pods for my deployment. A little while later, I refreshed the overview page and found that my Resource Deployment failed. The error, `"Back-off, Restarting Failed Container"` was listed. My 2 Pods had a status, `"Waiting: CrashLoopBackOff"`. 

Using the CLI, `az get pods` confirmed both pods were not running and that restarts were being attempted. I do believe that I would need to use a YAML file instead to create containers ( like I did successfully for Azure Container Instances ) so I am busy exploring this option right now. 

Has anyone used a YAML file in AKS or even Kubernetes to create a successfully deploy a pod ( or pods) for OSRM-Backend? 

I used the following YAML file in my attempts ( for `OSRM-Routed` ) but it is not uploading to Azure for some weird reason - I can't seem to figure out why Azure is not allowing this.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: osrm-backend
spec:
  selector:
    matchLabels:
      app: osrm-backend
  template:
    metadata:
      labels:
        app: osrm-backend
    spec:
      containers:
      - name: osrm-backend
        image: osrm-backend:custom
        command: ["osrm-routed"]
        args: ["--port", "5000", "--algorithm", "mld", "/mnt/osrm/berlin-latest.osrm"]
        ports:
        - containerPort: 5000
```

Would appreciate any assistance provided. 

Thanks!
