### ISSUE TITLE
Deployment of OSRM (Using YAML) on Azure Kubernetes Service

### ISSUE THREAD

**Issue by sheldonreddy** [Project-OSRM/osrm-backend#5643]
Hey OSRMDevs

**BLOT:**
I am encountering an issue when attempting to deploy OSRM on Kubernetes within the Azure Kubernetes Service (AKS). I need assistance building a YAML file for my OSRM Kubernetes deployment to AKS. 

**SOME BACKGROUND**

I have successfully deployed an Azure Container Instance(ACI) for OSRM. 

for reference, I used the following commands on Azure Command Line Interface ( CLI ) to deploy an OSRM ACI.

```
az group create --name osrm-aci-rg --location eastus

az container create -g osrm-aci-rg --name osrm --location eastus --image osrm/osrm-backend --command-line "osrm-extract -p /opt/car.lua /mnt/osrm/berlin-latest.osm.pbf" --azure-file-volume-share-name ADD YOUR FILESHARE NAME HERE --azure-file-volume-account-name ADD YOUR FILE VOLUME NAME--azure-file-volume-account-key ADD YOUR KEY HERE --azure-file-volume-mount-path /mnt/osrm --restart-policy Never

az container attach -g osrm-aci-rg --name osrm

az container create -g osrm-aci-rg --name osrm --location eastus --image osrm/osrm-backend --command-line "osrm-partition /mnt/osrm/berlin-latest.osrm"--azure-file-volume-share-name ADD YOUR FILESHARE NAME HERE --azure-file-volume-account-name ADD YOUR FILE VOLUME NAME--azure-file-volume-account-key ADD YOUR KEY HERE --azure-file-volume-mount-path /mnt/osrm --restart-policy Never

az container show -g osrm-aci-rg --name osrm --query "containers[0].instanceView.currentState.state"

az container create -g osrm-aci-rg --name osrm --location eastus --image osrm/osrm-backend --command-line "osrm-customize /mnt/osrm/berlin-latest.osrm"--azure-file-volume-share-name ADD YOUR FILESHARE NAME HERE --azure-file-volume-account-name ADD YOUR FILE VOLUME NAME--azure-file-volume-account-key ADD YOUR KEY HERE --azure-file-volume-mount-path /mnt/osrm --restart-policy Never

az container delete -g osrm-aci-rg --name osrm

az container create -g osrm-aci-rg --name osrm --location eastus --image osrm/osrm-backend --command-line "osrm-routed --port 80 --algorithm mld /mnt/osrm/berlin-latest.osrm" --azure-file-volume-share-name ADD YOUR FILESHARE NAME HERE --azure-file-volume-account-name berlinstore --azure-file-volume-account-key ADD YOUR KEY HERE --azure-file-volume-mount-path /mnt/osrm --dns-name-label osrmaci --ports 80

```

This successfully configures and deploys OSRM to an ACI and provides me with an endpoint URL which I can use to cURL my OSRM ACI with Coordinates. I do this as follows within CMD:

`curl "http://osrmaci.eastus.azurecontainer.io/route/v1/driving/13.388860,52.517037;13.385983,52.496891?overview=false"
`

I receive the correct response ( verified using Google Maps ).

**THE PROBLEM/ISSUE**

I would now like to deploy OSRM-Backend to Azure Kubernetes Service (AKS). 

_Architecture_
The architecture I have in my mind is as follows (I would appreciate any comments in this regard):
OSRM is deployed to a CONTAINER within a POD which runs on a worker NODE. 
AKS manages this worker node as well as the master node ( where the API Server, Scheduler, Controller-Manager and ETCD run). 

_Workflow_

As mentioned, I successfully deployed OSRM to ACI ( as seen in the code snippet above). 
I also deployed OSRM on my local machine.
The workflow for both these deployments was achieved with the following steps:
1. Perform the `osrm-extract` with parameters `cars.lua` and  `<country>-latest .osm.pbf` 
2. Perform the ` osrm-partition` command with parameter `<country>-latest.osrm` 
3. Perform the ` osrm-customize` command with parameter `<country>-latest.osrm` 
4. Perform the ` osrm-customize` command with parameter `<country>-latest.osrm` 
5. Perform the ` osrm-routed` command with parameters `port` , `algorithm` and `<country>-latest.osrm`

I am extremely unsure of how to build a YAML file to do the above steps. 

The structure of my YAML file is as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: osrmbackend
  labels:
    app: osrmbackend
spec:
  template:
    metadata:
      labels:
        app: osrmbackend
    spec:
      containers:
        - name: osrmbackend
          image: osrmo/osrm-backend
          command: ["osrm-extract"]
          args: ["<MY-AZURE-BLOB-STORAGE-PATH>/car.lua", "<MY-AZURE-BLOB-STORAGE-PATH>/<CountryName>-latest.osm.pbf"]
---
apiVersion: v1
kind: Pod
metadata:
  name: osrmbackend
  labels:
    app: osrmbackend
spec:
  template:
    metadata:
      labels:
        app: osrmbackend
    spec:
      containers:
        - name: osrmbackend
          image: osrmo/osrm-backend
          command: ["osrm-partition"]
          args: ["<MY-AZURE-BLOB-STORAGE-PATH>/<CountryName>-latest.osrm"]
---
apiVersion: v1
kind: Pod
metadata:
  name: osrmbackend
  labels:
    app: osrmbackend
spec:
  template:
    metadata:
      labels:
        app: osrmbackend
    spec:
      containers:
        - name: osrmbackend
          image: osrmo/osrm-backend
          command: ["osrm-customize"]
          args: ["<MY-AZURE-BLOB-STORAGE-PATH>/<CountryName>-latest.osrm"]
---
apiVersion: v1
kind: Pod
metadata:
  name: osrmbackend
  labels:
    app: osrmbackend
spec:
  template:
    metadata:
      labels:
        app: osrmbackend
    spec:
      containers:
        - name: osrmbackend
          image: osrmo/osrm-backend
          command: ["osrm-routed"]
          args: ["--port 80", "--algorithm mld", "<MY-AZURE-BLOB-STORAGE-PATH>/<CountryName>-latest.osrm"]
          ports: 
            -containerPort: 80

```

The deployment does not even start - pointing to a YAML issue.
I just can't seem to figure out what is causing this. I have verified, using a YAML file validator, that all is in order in respect of the Syntax and indentation used to create the YAML file.  

I would greatly appreciate any advice to assist me in creating a valid YAML file for deployment of OSRM to Azure Kubernetes Service.

Thank you
