### ISSUE TITLE
Unexpected result with table-service and rush hour data

### ISSUE THREAD

**Issue by knasti** [Project-OSRM/osrm-backend#5723]
I've been getting rush-hour data up on OSRM v5.22.0, and have run into an issue, which I think is a bug.

After applying the rush-hour data I noticed that the results from the [table-service](http://project-osrm.org/docs/v5.5.1/api/#table-service) for normal car and rush hour are almost identical. This had me thinking, as the log file told me that the values from the rush-hour traffic csv file were indeed loaded. I confirmed this by taking a look of the speeds and datasource of the speeds from a tile generated through the [tile-service](http://project-osrm.org/docs/v5.5.1/api/#tile-service).

So I tried to use the [route-service](http://project-osrm.org/docs/v5.5.1/api/#route-service) to check if it gives the same results. Requests and responses from the route- and table-service are shown below.

**Route request**
http://osrm-rush-hour:5000/route/v1/driving/10.38540952,55.39372974;12.5837,55.638711?annotations=true

**Route response**
[response_route.txt](https://github.com/Project-OSRM/osrm-backend/files/4532503/response_route.txt)

**Table request**
http://osrm-rush-hour:5000/table/v1/driving/10.38540952,55.39372974;12.5837,55.638711

**Table response**
[response_table.txt](https://github.com/Project-OSRM/osrm-backend/files/4532501/response_table.txt)

The table service gives me back a duration of 6745 and the route service 8173. The result from the route service seems correct to me. I suspect that the table-service somehow ignores the rush-hour csv file I used for speeds, and uses the lua file on all edges, because, as I mentioned earlier, the normal car and rush-hour are almost identical.

Another oddity I noted is that, under the route response it only lists the lua profile under datasource_names. Even though I'm quite sure that the route service does indeed use the rush hour csv I supplied.

Let me hear what you think.

**Comment by danpat** [comment]
Check to make sure you don't have multiple `osrm-routed` processes running - OSRM will share the TCP socket with other `osrm-routed` processes, so if you have an old one running, you may be getting responses from both your old process and your updated process.

**Comment by knasti** [comment]
I see. I am running multiple osrm-routed processes in my docker-compose for different transport modes (bike, car and rush-hour). Is it bad practice to do that? I thought it might not be from some other threads like [Documentation](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM#running-multiple-profiles-on-one-machine) and #4517.

Example from docker-compose file:
```
services:
  osrm:
    restart: always
    build:
      context: ./osrm/car
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: bash -c "osrm-routed --algorithm mld denmark-latest.osrm --max-table-size 100000 --max-viaroute-size 15000 --max-trip-size=10000"
  osrm-rush-hour:
    restart: always
    build:
      context: ./osrm/rush_hour
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    command: bash -c "osrm-routed --algorithm mld denmark-latest.osrm --max-table-size 100000 --max-viaroute-size 15000 --max-trip-size=10000"
```

However, when I turn the others osrm containers off so that only osrm-routed for rush-hour runs I still seem to get the same result as above. Also I haven't had issues with the bike and car osrm-routed processes affect each others results.
