### ISSUE TITLE
Unable to deploy using docker-compose

### ISSUE THREAD

**Issue by stephenhenckaerts** [Project-OSRM/osrm-backend#6160]
I am trying to create a docker-compose file that creates a osrm-backend container with the latest version of osrm-backend. 

When the `docker-compose up` is executed, we get the following error message `osrm exited with code 0`. 

Below I have pasted the yml file. The 'osm.pbf' file is located inside the ./data folder that is located in the same directory as the .yml.

```
version: "1"
services:
  osrm:
    container_name: osrm
    image: osrm/osrm-backend:latest
    restart: always
    ports:
      - "8091:5000"
    volumes:
      - ./data/:/data/
```
